### ISSUE TITLE
Quand le renard n'a aucun coup à disposition

### ISSUE THREAD

**Issue by Denis-Vekemans** [jfromentin/fox#2]
Par exemple sur -3, +3 comme coups du renard et 4 terriers, si le renard commence sur un terrier qui n'est pas extrémal, le jeu du renard est impossible ...
Je propose de rajouter une condition comme max des coups - min des coups <= nombre de terriers pour que le renard ait toujours au moins un coup à disposition.

**Comment by jfromentin** [comment]
Done.
